### ISSUE TITLE
DDC-3739: [GH-1410] Skip generate lifecycle methods if they already generated

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/orm#4577]
Jira issue originally created by user @doctrinebot:

This issue is created automatically through a Github pull request on behalf of aivus:

Url: https://github.com/doctrine/doctrine2/pull/1410

Message:

This happens when I use one lifecycle method in prePersist and preUpdate together. Like

``` yml
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]
```

Before generator generate two methods with the same names.

@Ocramius, what do you think what is better way to write test for this?
Should I test generateEntityLifecycleCallbackMethods directly?
