### ISSUE TITLE
InvalidArgumentException - Unable to create a proxy for a final class

### ISSUE THREAD

**Issue by JamieYnonan** [doctrine/orm#7598]
|    Q        |   A
|------------ | -----
| Version     | 2.6.3

### Support Question

I can't use final class?

`InvalidArgumentException Unable to create a proxy for a final class "Mu\Domain\Model\Role\Role"`

final class Role
```
Mu\Domain\Model\Role\Role:
  type: entity
  table: roles
  id:
    id:
      type: role_id
      generator:
        strategy: NONE
  embedded:
    name:
      class: Mu\Domain\Model\Role\Name
      columnPrefix: false
    description:
      class: Mu\Domain\Model\Role\Description
      columnPrefix: false
    status:
      class: Mu\Domain\Model\Role\Status
      columnPrefix: false
  fields:
    updatedAt:
      type: datetimetz
      column: updated_at
    createdAt:
      type: datetimetz
      column: created_at
  manyToMany:
    permissions:
      fetch: EXTRA_LAZY
      targetEntity: Mu\Domain\Model\Permission\Permission
      joinTable:
        name: role_permissions
        joinColumns:
          role_id:
            referencedColumnName: id
        inverseJoinColumns:
          permission_id:
            referencedColumnName: id
```

final class User
```
Mu\Domain\Model\User\User:
  type: entity
  table: users
  id:
    id:
      type: user_id
      generator:
        strategy: NONE
  embedded:
    name:
      class: Mu\Domain\Model\User\Name
      columnPrefix: false
    lastName:
      class: Mu\Domain\Model\User\LastName
      columnPrefix: false
    email:
      class: Mu\Domain\Model\User\Email
      columnPrefix: false
    password:
      class: Mu\Domain\Model\User\Password
      columnPrefix: false
    status:
      class: Mu\Domain\Model\User\Status
      columnPrefix: false
  fields:
    updatedAt:
      type: datetimetz
      column: updated_at
    createdAt:
      type: datetimetz
      column: created_at
  manyToOne:
    role:
      fetch: EXTRA_LAZY
      targetEntity: Mu\Domain\Model\Role\Role
      joinColumn:
        role_id:
          referencedColumnName: id
          nullable: false
```
