### ISSUE TITLE
Resolving target entities from abstract class seems to not working as expected

### ISSUE THREAD

**Issue by emulienfou** [doctrine/orm#7670]
Hello, according to the [How to Define Relationships with Abstract Classes and Interfaces](https://symfony.com/doc/current/doctrine/resolve_target_entity.html), I should be able to use the `ResolveTargetEntityListener` to resolve an abstract class to a specific entity.

**However, this "feature" seems to not working properly.**

## 1. Using an interface
Here is the PHP code used to resolve the interface to the entity class;
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(RedirectRouteInterface::class)
    ->getName();
```
> **$registry** is an instance of `\Doctrine\Common\Persistence\ManagerRegistry`

When configuring doctrine using an interface like:
```yaml
doctrine:
    orm:
        resolve_target_entities:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: App\Entity\RedirectRoute
```
everything is working perfectly and the name is equals to `App\Entity\RedirectRoute`

## 2. Using an abstract class
Now when I'm trying to resolve an entity from an abstract class, the resolver seems to not working properly.
Here is the PHP code used to resolve the abstract class to the entity class:
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(AbstractRedirectRoute::class)
    ->getName();
```
> **$registry** is an instance of `\Doctrine\Common\Persistence\ManagerRegistry`

When configuring doctrine using an abstract class like:
```yaml
doctrine:
    orm:
        resolve_target_entities:
            App\Model\AbstractRedirectRoute: App\Entity\RedirectRoute
```
In that case, the resolver is returning the abstract class FQCN: `App\Model\AbstractRedirectRoute`.

Weird thing is, to be able to resolve the abstract class I need to make the call to `getAllMetadata()` method like:
```php
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getAllMetadata();
$registry
    ->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(AbstractRedirectRoute::class)
    ->getName();
```
In that case, the entity is resolved correctly!

---
**Is this an issue or more a miss-configuration on my side?**
