### ISSUE TITLE
Cache: READ_WRITE failing `Argument 2 passed to...`

### ISSUE THREAD

**Issue by NikoGrano** [doctrine/orm#7981]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.7.0

#### Summary

Entity:
```
 * @ORM\Entity
 * @ORM\Table(name="stock_inventory")
 * @ORM\Cache(usage="READ_WRITE", region="locking")
```

Configuration (Bundle for Symfony)
```yaml
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: cache.doctrine.redis
                        pool: 'dl2_'
                    enabled: true
                    regions:
                        locking:
                            cache_driver:
                                type: service
                                id: cache.doctrine.redis
                                pool: 'dl2l_'
                            lock_path: '%kernel.cache_dir%/doctrine/orm/lock'
```

**While correct configuration would be**
```yaml
    orm:
        ...
        entity_managers:
            default:
                ...
                second_level_cache:
                    ...
                    regions:
                        locking:
                            lock_path: '%kernel.cache_dir%/doctrine/orm/lock'
                            type: filelock
```

#### Current behavior

Running a write into the database will cause
```php
 [TypeError]                                                                                                                                                                                                     
  Argument 2 passed to Doctrine\ORM\Cache\Persister\Entity\ReadWriteCachedEntityPersister::__construct() must be an instance of Doctrine\ORM\Cache\ConcurrentRegion, instance of Doctrine\ORM\Cache\Region\Defau  
  ltRegion given, called in /app/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php on line 132  

Exception trace:
  at /app/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersister.php:44
 Doctrine\ORM\Cache\Persister\Entity\ReadWriteCachedEntityPersister->__construct() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php:132
 Doctrine\ORM\Cache\DefaultCacheFactory->buildCachedEntityPersister() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3133
 Doctrine\ORM\UnitOfWork->getEntityPersister() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1065
 Doctrine\ORM\UnitOfWork->executeInserts() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:400
 Doctrine\ORM\UnitOfWork->commit() at /app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:368
 Doctrine\ORM\EntityManager->flush() at projectRelatedFile.php:50
```

#### Digging the issue
So this is caused due [here](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php#L72) we are expecting Region interface. This is propably correct functionality. [Here](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php#L100) we pass it to the next class, which causes this error. The problem is, in the Persister [constructor](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/Persister/Entity/ReadWriteCachedEntityPersister.php#L24) we are declaring we want this one specific type.

This should be fixed with a interface, abstract class or something. Any toughts? Or is this something for 3.0/wontfix?


#### How to reproduce

Configure previous settings and try persist something to the database.

#### Expected behavior

Throw a handled exception, not a type error. 

#### Notes
I'm not sure how this architecture fully works, so I would like if somebody else familiar with this would take this. With correct configuration this works, but I wasn't sure if I should post bug about this, however I decided to post it just to make sure this is intended functionality.
