### ISSUE TITLE
Processes an individual parameter value with embeddables

### ISSUE THREAD

**Issue by amelendres** [doctrine/orm#8063]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.1

#### Summary

Queries with embeddable parameters has an error.
trying to access to a hardcoded undefined index 0.

message = "Notice: Undefined offset: 0"
line = {int} 730
file = "/app
![Screen Shot 2020-03-10 at 13 42 26](https://user-images.githubusercontent.com/1708652/76313333-0898a900-62d5-11ea-84e0-ff3c2645694b.png)
/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php"
severity = {int} 8
*Exception*string = ""
code = {int} 0

**trace:**
  file = "/app/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php"
  line = {int} 424
  function = "getSingleIdentifierValue"
  class = "Doctrine\ORM\UnitOfWork"
  type = "->"

#### Current behavior

Imposible to create a query with query builder using embeddable value objects.

#### Expected behavior

execute the query

**Comment by SenseException** [comment]
Please add your DQL Query and involved entities + mappings that is causing this error.

**Comment by amelendres** [comment]
DQL:
 `SELECT a FROM Appto\Booking\Domain\Availability\Availability a WHERE a.boatId.value = :boatId AND a.portId.value = :portId AND ((a.timePeriod.startDate BETWEEN :start AND :end) OR (a.timePeriod.endDate BETWEEN :start AND :end)) ORDER BY a.timePeriod.startDate ASC`

```
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                          https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Appto\Booking\Domain\Availability\Availability" table="boo_availability" >
        <embedded name="id" class="Appto\Booking\Domain\Availability\AvailabilityId" use-column-prefix="false"/>
        <embedded name="boatId" class="Appto\Booking\Domain\Availability\BoatId" use-column-prefix="false"/>
        <embedded name="portId" class="Appto\Booking\Domain\Availability\PortId" use-column-prefix="false"/>
        <embedded name="timePeriod" class="Appto\Common\Domain\DateTime\TimePeriod"/>
        <embedded name="dailyPrice" class="Appto\Common\Domain\Money\Price"/>
    </entity>
</doctrine-mapping>


<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                          https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
        <embeddable name="Appto\Booking\Domain\Availability\BoatId">
            <field name="value" type="guid" column="boat_id" />
        </embeddable>
</doctrine-mapping>

```

**Comment by blackandred** [comment]
Same there.

```sql
SELECT usr FROM App\Domain\Users\WriteModel\User usr WHERE usr.email.value = :email
```

```yaml
App\Domain\Users\WriteModel\User:
    type: entity
    table: users

    id:
        id:
            type: guid
            generator:
                strategy: UUID

    embedded:
        email:
            class: App\Domain\Users\ValueObject\Email
            columnPrefix: false

        password:
            class: App\Domain\Users\ValueObject\Password
            columnPrefix: false

        organization:
            class: App\Domain\Users\ValueObject\Organization
            columnPrefix: false

        about:
            class: App\Domain\Users\ValueObject\About
            columnPrefix: false

        roles:
            class: App\Domain\Users\Collection\RolesCollection
            columnPrefix: false

    fields:
        salt:
            type: string
            length: 32

```
