### ISSUE TITLE
Doctrine_Collection forgets it is part of a reference when serialized

### ISSUE THREAD

**Issue by spaanse** [doctrine/orm#8250]
Short description:
A Doctrine_Collection does not remember it's `_referenceField` under serialisation. This means that under serialisation/unseralisation any new members don't get their reference updated.

Let there be two database tables `Foo` and `Bar`, where there is a one-to-many relation between them:

```yml
Foo:
  tableName: tblfoo
  columns:
    foo_id: {primary: true, type: integer(4), autoincrement: true}
  relations:
    Bar:
      local: foo_id
      foreign: bar_foo_id
Bar:
  tableName: tblbar
  columns:
    bar_id: {primary: true, type: integer(4), autoincrement: true}
    bar_foo_id: integer(4)
  relations:
    Foo:
      local: bar_foo_id
      foreign: foo_id
```

Then when the following code is run the output is null instead of a Foo object:

```php
$foo = new Foo();
$cache = serialize($foo);
...
$foo = unserialize($cache)
$bar = new Bar();
$foo->Bar->add($bar);
return $bar->Foo;
```

This is because the Doctrine_Collection $foo->Bar has cleared it's `_referenceField` under serialisation. Then after being unserialised it is just a normal Doctrine_Collection, so does not automatically set $bar->Foo when adding the object.
